CREATE TABLE country(
   alpha_2_code TEXT NOT NULL
  ,alpha_3_code TEXT NOT NULL
  ,id           TEXT NOT NULL PRIMARY KEY
  ,name         TEXT NOT NULL
);
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('AF','AFG','AF','Afghanistan');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('AX','ALA','AX','Åland Islands');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('AL','ALB','AL','Albania');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('DZ','DZA','DZ','Algeria');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('AS','ASM','AS','American Samoa');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('AD','AND','AD','Andorra');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('AO','AGO','AO','Angola');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('AI','AIA','AI','Anguilla');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('AQ','ATA','AQ','Antarctica');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('AG','ATG','AG','Antigua and Barbuda');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('AR','ARG','AR','Argentina');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('AM','ARM','AM','Armenia');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('AW','ABW','AW','Aruba');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('AU','AUS','AU','Australia');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('AT','AUT','AT','Austria');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('AZ','AZE','AZ','Azerbaijan');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('BS','BHS','BS','Bahamas');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('BH','BHR','BH','Bahrain');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('BD','BGD','BD','Bangladesh');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('BB','BRB','BB','Barbados');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('BY','BLR','BY','Belarus');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('BE','BEL','BE','Belgium');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('BZ','BLZ','BZ','Belize');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('BJ','BEN','BJ','Benin');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('BM','BMU','BM','Bermuda');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('BT','BTN','BT','Bhutan');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('BO','BOL','BO','Bolivia (Plurinational State of)');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('BQ','BES','BQ','Bonaire, Sint Eustatius and Saba');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('BA','BIH','BA','Bosnia and Herzegovina');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('BW','BWA','BW','Botswana');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('BV','BVT','BV','Bouvet Island');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('BR','BRA','BR','Brazil');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('IO','IOT','IO','British Indian Ocean Territory');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('UM','UMI','UM','United States Minor Outlying Islands');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('VG','VGB','VG','Virgin Islands (British)');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('VI','VIR','VI','Virgin Islands (U.S.)');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('BN','BRN','BN','Brunei Darussalam');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('BG','BGR','BG','Bulgaria');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('BF','BFA','BF','Burkina Faso');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('BI','BDI','BI','Burundi');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('KH','KHM','KH','Cambodia');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('CM','CMR','CM','Cameroon');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('CA','CAN','CA','Canada');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('CV','CPV','CV','Cabo Verde');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('KY','CYM','KY','Cayman Islands');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('CF','CAF','CF','Central African Republic');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('TD','TCD','TD','Chad');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('CL','CHL','CL','Chile');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('CN','CHN','CN','China');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('CX','CXR','CX','Christmas Island');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('CC','CCK','CC','Cocos (Keeling) Islands');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('CO','COL','CO','Colombia');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('KM','COM','KM','Comoros');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('CG','COG','CG','Congo');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('CD','COD','CD','Congo (Democratic Republic of the)');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('CK','COK','CK','Cook Islands');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('CR','CRI','CR','Costa Rica');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('HR','HRV','HR','Croatia');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('CU','CUB','CU','Cuba');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('CW','CUW','CW','Curaçao');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('CY','CYP','CY','Cyprus');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('CZ','CZE','CZ','Czech Republic');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('DK','DNK','DK','Denmark');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('DJ','DJI','DJ','Djibouti');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('DM','DMA','DM','Dominica');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('DO','DOM','DO','Dominican Republic');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('EC','ECU','EC','Ecuador');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('EG','EGY','EG','Egypt');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('SV','SLV','SV','El Salvador');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('GQ','GNQ','GQ','Equatorial Guinea');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('ER','ERI','ER','Eritrea');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('EE','EST','EE','Estonia');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('ET','ETH','ET','Ethiopia');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('FK','FLK','FK','Falkland Islands (Malvinas)');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('FO','FRO','FO','Faroe Islands');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('FJ','FJI','FJ','Fiji');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('FI','FIN','FI','Finland');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('FR','FRA','FR','France');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('GF','GUF','GF','French Guiana');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('PF','PYF','PF','French Polynesia');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('TF','ATF','TF','French Southern Territories');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('GA','GAB','GA','Gabon');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('GM','GMB','GM','Gambia');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('GE','GEO','GE','Georgia');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('DE','DEU','DE','Germany');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('GH','GHA','GH','Ghana');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('GI','GIB','GI','Gibraltar');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('GR','GRC','GR','Greece');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('GL','GRL','GL','Greenland');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('GD','GRD','GD','Grenada');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('GP','GLP','GP','Guadeloupe');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('GU','GUM','GU','Guam');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('GT','GTM','GT','Guatemala');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('GG','GGY','GG','Guernsey');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('GN','GIN','GN','Guinea');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('GW','GNB','GW','Guinea-Bissau');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('GY','GUY','GY','Guyana');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('HT','HTI','HT','Haiti');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('HM','HMD','HM','Heard Island and McDonald Islands');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('VA','VAT','VA','Holy See');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('HN','HND','HN','Honduras');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('HK','HKG','HK','Hong Kong');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('HU','HUN','HU','Hungary');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('IS','ISL','IS','Iceland');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('IN','IND','IN','India');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('ID','IDN','ID','Indonesia');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('CI','CIV','CI','Côte d''Ivoire');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('IR','IRN','IR','Iran (Islamic Republic of)');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('IQ','IRQ','IQ','Iraq');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('IE','IRL','IE','Ireland');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('IM','IMN','IM','Isle of Man');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('IL','ISR','IL','Israel');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('IT','ITA','IT','Italy');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('JM','JAM','JM','Jamaica');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('JP','JPN','JP','Japan');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('JE','JEY','JE','Jersey');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('JO','JOR','JO','Jordan');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('KZ','KAZ','KZ','Kazakhstan');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('KE','KEN','KE','Kenya');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('KI','KIR','KI','Kiribati');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('KW','KWT','KW','Kuwait');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('KG','KGZ','KG','Kyrgyzstan');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('LA','LAO','LA','Lao People''s Democratic Republic');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('LV','LVA','LV','Latvia');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('LB','LBN','LB','Lebanon');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('LS','LSO','LS','Lesotho');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('LR','LBR','LR','Liberia');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('LY','LBY','LY','Libya');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('LI','LIE','LI','Liechtenstein');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('LT','LTU','LT','Lithuania');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('LU','LUX','LU','Luxembourg');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('MO','MAC','MO','Macao');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('MK','MKD','MK','Macedonia (the former Yugoslav Republic of)');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('MG','MDG','MG','Madagascar');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('MW','MWI','MW','Malawi');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('MY','MYS','MY','Malaysia');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('MV','MDV','MV','Maldives');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('ML','MLI','ML','Mali');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('MT','MLT','MT','Malta');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('MH','MHL','MH','Marshall Islands');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('MQ','MTQ','MQ','Martinique');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('MR','MRT','MR','Mauritania');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('MU','MUS','MU','Mauritius');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('YT','MYT','YT','Mayotte');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('MX','MEX','MX','Mexico');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('FM','FSM','FM','Micronesia (Federated States of)');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('MD','MDA','MD','Moldova (Republic of)');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('MC','MCO','MC','Monaco');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('MN','MNG','MN','Mongolia');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('ME','MNE','ME','Montenegro');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('MS','MSR','MS','Montserrat');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('MA','MAR','MA','Morocco');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('MZ','MOZ','MZ','Mozambique');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('MM','MMR','MM','Myanmar');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('NA','NAM','NA','Namibia');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('NR','NRU','NR','Nauru');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('NP','NPL','NP','Nepal');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('NL','NLD','NL','Netherlands');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('NC','NCL','NC','New Caledonia');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('NZ','NZL','NZ','New Zealand');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('NI','NIC','NI','Nicaragua');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('NE','NER','NE','Niger');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('NG','NGA','NG','Nigeria');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('NU','NIU','NU','Niue');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('NF','NFK','NF','Norfolk Island');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('KP','PRK','KP','Korea (Democratic People''s Republic of)');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('MP','MNP','MP','Northern Mariana Islands');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('NO','NOR','NO','Norway');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('OM','OMN','OM','Oman');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('PK','PAK','PK','Pakistan');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('PW','PLW','PW','Palau');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('PS','PSE','PS','Palestine, State of');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('PA','PAN','PA','Panama');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('PG','PNG','PG','Papua New Guinea');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('PY','PRY','PY','Paraguay');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('PE','PER','PE','Peru');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('PH','PHL','PH','Philippines');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('PN','PCN','PN','Pitcairn');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('PL','POL','PL','Poland');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('PT','PRT','PT','Portugal');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('PR','PRI','PR','Puerto Rico');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('QA','QAT','QA','Qatar');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('XK','KOS','XK','Republic of Kosovo');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('RE','REU','RE','Réunion');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('RO','ROU','RO','Romania');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('RU','RUS','RU','Russian Federation');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('RW','RWA','RW','Rwanda');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('BL','BLM','BL','Saint Barthélemy');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('SH','SHN','SH','Saint Helena, Ascension and Tristan da Cunha');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('KN','KNA','KN','Saint Kitts and Nevis');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('LC','LCA','LC','Saint Lucia');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('MF','MAF','MF','Saint Martin (French part)');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('PM','SPM','PM','Saint Pierre and Miquelon');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('VC','VCT','VC','Saint Vincent and the Grenadines');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('WS','WSM','WS','Samoa');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('SM','SMR','SM','San Marino');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('ST','STP','ST','Sao Tome and Principe');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('SA','SAU','SA','Saudi Arabia');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('SN','SEN','SN','Senegal');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('RS','SRB','RS','Serbia');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('SC','SYC','SC','Seychelles');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('SL','SLE','SL','Sierra Leone');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('SG','SGP','SG','Singapore');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('SX','SXM','SX','Sint Maarten (Dutch part)');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('SK','SVK','SK','Slovakia');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('SI','SVN','SI','Slovenia');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('SB','SLB','SB','Solomon Islands');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('SO','SOM','SO','Somalia');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('ZA','ZAF','ZA','South Africa');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('GS','SGS','GS','South Georgia and the South Sandwich Islands');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('KR','KOR','KR','Korea (Republic of)');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('SS','SSD','SS','South Sudan');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('ES','ESP','ES','Spain');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('LK','LKA','LK','Sri Lanka');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('SD','SDN','SD','Sudan');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('SR','SUR','SR','Suriname');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('SJ','SJM','SJ','Svalbard and Jan Mayen');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('SZ','SWZ','SZ','Swaziland');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('SE','SWE','SE','Sweden');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('CH','CHE','CH','Switzerland');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('SY','SYR','SY','Syrian Arab Republic');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('TW','TWN','TW','Taiwan');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('TJ','TJK','TJ','Tajikistan');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('TZ','TZA','TZ','Tanzania, United Republic of');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('TH','THA','TH','Thailand');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('TL','TLS','TL','Timor-Leste');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('TG','TGO','TG','Togo');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('TK','TKL','TK','Tokelau');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('TO','TON','TO','Tonga');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('TT','TTO','TT','Trinidad and Tobago');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('TN','TUN','TN','Tunisia');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('TR','TUR','TR','Turkey');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('TM','TKM','TM','Turkmenistan');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('TC','TCA','TC','Turks and Caicos Islands');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('TV','TUV','TV','Tuvalu');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('UG','UGA','UG','Uganda');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('UA','UKR','UA','Ukraine');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('AE','ARE','AE','United Arab Emirates');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('GB','GBR','GB','United Kingdom of Great Britain and Northern Ireland');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('US','USA','US','United States of America');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('UY','URY','UY','Uruguay');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('UZ','UZB','UZ','Uzbekistan');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('VU','VUT','VU','Vanuatu');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('VE','VEN','VE','Venezuela (Bolivarian Republic of)');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('VN','VNM','VN','Viet Nam');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('WF','WLF','WF','Wallis and Futuna');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('EH','ESH','EH','Western Sahara');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('YE','YEM','YE','Yemen');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('ZM','ZMB','ZM','Zambia');
INSERT INTO country(alpha_2_code,alpha_3_code,id,name) VALUES ('ZW','ZWE','ZW','Zimbabwe');
